spring:
  application:
    name: buyer-order
  datasource:
    url: jdbc:mysql://localhost:3306/buyer_order?characterEncoding=utf8&serverTimezone=UTC
    name: buyer_order
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 50
    max-wait: 100
    min-idle: 10
    test-on-borrow: true
    validation-query: SELECT 1
    username: root
    password: 123456
  flyway:
    locations: classpath:/db/migration
    enabled: true
    outOfOrder: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8080

feign:
  stock:
    url:  http://localhost:7300/mock/613dbf4f98a80d0027074696/stock