version: '3'

services:
  mongodb:
    image: mongo:3.4.1
#    volumes:
#      - '/apps/easy-mock/data/db:/Users/mo.zhou/workspace/log/mongo/data'
    networks:
      - easy-mock
    restart: always

  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
#    volumes:
#      - '/apps/easy-mock/data/redis:/Users/mo.zhou/workspace/log/redis/data'
    networks:
      - easy-mock
    restart: always

  web:
    image: easymock/easymock:1.6.0
    command: /bin/bash -c "npm run dev"
    ports:
      - 7300:7300
#    volumes:
#      - '/apps/easy-mock/logs:/Users/mo.zhou/workspace/log/easy-mock/data'
    networks:
      - easy-mock
    restart: always

networks:
  easy-mock: